RedPetroleum/RedPetroleumWeb/Controllers/BansController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using RedPetroleumAction.Data.Repositories;

namespace RedPetroleumWeb.Controllers
{
    [Authorize]
    public class BansController : Controller
    {
        private IBansRepository _bansRepository;

        public BansController(IBansRepository bansRepository)
        {
            _bansRepository = bansRepository;
        }

        // GET: Bans
        public async Task<ActionResult> Index()
        {
            return View(await _bansRepository.GetAll().OrderByDescending(x=>x.DateCreate).ToListAsync());
        }

        // GET: Projects/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var ban = await _bansRepository.GetBy(x => x.Id == id).FirstOrDefaultAsync();
            if (ban == null)
            {
                return HttpNotFound();
            }
            return View(ban);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if (id == null)
            {
                return View();
            }
            var ban = await _bansRepository.GetBy(x => x.Id == id).FirstOrDefaultAsync();
            if (ban == null) return View();
            _bansRepository.Remove(ban);
            _bansRepository.Save();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _bansRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RedPetroleum/RedPetroleumWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("RED PETROLEUM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Главная", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("О нас", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Проверка купона", "CheckPointsIsRegister", "Home")</li>
                    <li>@Html.ActionLink("Баны", "Index", "Bans")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Red Petroleum</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jslinq")
    @RenderSection("scripts", required: false)
</body>
</html>